### ISSUE TITLE
I think we should axe all usage of this in favor of JWK

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/web5-kt#149]
I think we should axe all usage of this in favor of JWK

_Originally posted by @decentralgabe in https://github.com/TBD54566975/web5-kt/pull/146#discussion_r1402702054_

**Comment by jiyoontbd** [comment]
i think it's safe to close this, because
1. the codebase has now drifted away from when this PR comment was made 
2. we've now created our own `VerificationMethod` type
3. we are currently in the process of creating our own `JWK` type

if anyone disagrees, please feel free to open a new ticket with more details. thank you 🙏
